services:
    tee:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - tee:/app/packages/client-twitter/src/tweetcache
            - tee:/app/db.sqlite
        environment:
            - TWITTER_DRY_RUN=false
            - SLIPPAGE=1
            - SERVER_PORT=3000
        ports:
            - "3000:3000"
        restart: always
volumes:
    tee:
