services:
    tee:
        container_name: eliza-agent
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - tee:/app/packages/client-twitter/src/tweetcache
            - tee:/app/db.sqlite
            - .:/app
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - TWITTER_DRY_RUN=false
            - SLIPPAGE=1
            - SERVER_PORT=3000
            - RABBITMQ_URL=${RABBITMQ_URL}
        ports:
            - "3000:3000"
        restart: always
        command: sh -c "pnpm build && pnpm start"
        networks:
            - shared-network

networks:
    shared-network:
        external: true

volumes:
    tee:
